phpconfig.content:
  path: '/phpconfig'
  defaults:
    _controller: 'Drupal\phpconfig\Controller\PhpConfigController::content'
    _title: 'Hello world'
  requirements:
    _permission: 'access content'