phpconfig.index:
  path: '/admin/config/development/phpconfig'
  defaults:
    _controller: 'Drupal\phpconfig\Controller\PhpConfigController::index'
    _title: 'PHP config list'
  requirements:
    _permission: 'administer phpconfig'
phpconfig.test:
  path: '/admin/config/development/phpconfig/test'
  defaults:
    _controller: 'Drupal\phpconfig\Controller\PhpConfigController::test'
    _title: 'PHP config test'
  requirements:
    _permission: 'administer phpconfig'
phpconfig.form.add:
  path: '/admin/config/development/phpconfig/add'
  defaults:
    _form: 'Drupal\phpconfig\Form\PhpConfigForm'
    _title: 'PHP config list'
  requirements:
    _permission: 'administer phpconfig'
phpconfig.form.edit:
  path: '/admin/config/development/phpconfig/{configid}/edit'
  defaults:
    _form: 'Drupal\phpconfig\Form\PhpConfigForm'
    _title: 'PHP config list'
  requirements:
    _permission: 'administer phpconfig'